# Generated by Django 5.2.5 on 2025-09-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_person_id_alter_person_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('visitor', 'VISITOR'), ('resident', 'RESIDENT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.person'),
        ),
    ]
